//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalShopping.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbProjectEntities : DbContext
    {
        public dbProjectEntities()
            : base("name=dbProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCart> tblCarts { get; set; }
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblCompare> tblCompares { get; set; }
        public virtual DbSet<tblOrder> tblOrders { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
        public virtual DbSet<tblRetailer> tblRetailers { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblWishlist> tblWishlists { get; set; }
    
        public virtual int proc_Add_To_Wishlist(Nullable<int> productid, string useremail)
        {
            var productidParameter = productid.HasValue ?
                new ObjectParameter("productid", productid) :
                new ObjectParameter("productid", typeof(int));
    
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_Add_To_Wishlist", productidParameter, useremailParameter);
        }
    
        public virtual int proc_Approve_Product(Nullable<int> productid)
        {
            var productidParameter = productid.HasValue ?
                new ObjectParameter("productid", productid) :
                new ObjectParameter("productid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_Approve_Product", productidParameter);
        }
    
        public virtual int proc_Approve_Retailer(Nullable<int> retailerid, string retaileremail)
        {
            var retaileridParameter = retailerid.HasValue ?
                new ObjectParameter("retailerid", retailerid) :
                new ObjectParameter("retailerid", typeof(int));
    
            var retaileremailParameter = retaileremail != null ?
                new ObjectParameter("retaileremail", retaileremail) :
                new ObjectParameter("retaileremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_Approve_Retailer", retaileridParameter, retaileremailParameter);
        }
    
        public virtual int proc_Changepass(string rmail, string rpass)
        {
            var rmailParameter = rmail != null ?
                new ObjectParameter("rmail", rmail) :
                new ObjectParameter("rmail", typeof(string));
    
            var rpassParameter = rpass != null ?
                new ObjectParameter("rpass", rpass) :
                new ObjectParameter("rpass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_Changepass", rmailParameter, rpassParameter);
        }
    
        public virtual ObjectResult<proc_DisplayProducts_Result> proc_DisplayProducts(string rmail)
        {
            var rmailParameter = rmail != null ?
                new ObjectParameter("rmail", rmail) :
                new ObjectParameter("rmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_DisplayProducts_Result>("proc_DisplayProducts", rmailParameter);
        }
    
        public virtual ObjectResult<proc_DisplayRetailerDetails_Result> proc_DisplayRetailerDetails(string rmail)
        {
            var rmailParameter = rmail != null ?
                new ObjectParameter("rmail", rmail) :
                new ObjectParameter("rmail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_DisplayRetailerDetails_Result>("proc_DisplayRetailerDetails", rmailParameter);
        }
    
        public virtual ObjectResult<proc_Get_All_Retailers_Result> proc_Get_All_Retailers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_All_Retailers_Result>("proc_Get_All_Retailers");
        }
    
        public virtual ObjectResult<proc_Get_AllProducts_Result> proc_Get_AllProducts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_AllProducts_Result>("proc_Get_AllProducts");
        }
    
        public virtual ObjectResult<proc_Get_Cart_Total_Result> proc_Get_Cart_Total(string useremail)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_Cart_Total_Result>("proc_Get_Cart_Total", useremailParameter);
        }
    
        public virtual ObjectResult<proc_Get_Categories_Result> proc_Get_Categories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_Categories_Result>("proc_Get_Categories");
        }
    
        public virtual ObjectResult<proc_Get_Pending_Retailers_Result> proc_Get_Pending_Retailers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_Pending_Retailers_Result>("proc_Get_Pending_Retailers");
        }
    
        public virtual ObjectResult<proc_Get_Profile_User_Result> proc_Get_Profile_User(string useremail)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_Profile_User_Result>("proc_Get_Profile_User", useremailParameter);
        }
    
        public virtual ObjectResult<proc_Get_User_Orders_Result> proc_Get_User_Orders(string useremail)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_User_Orders_Result>("proc_Get_User_Orders", useremailParameter);
        }
    
        public virtual ObjectResult<proc_Get_User_Orders1_Result> proc_Get_User_Orders1(string useremail)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_User_Orders1_Result>("proc_Get_User_Orders1", useremailParameter);
        }
    
        public virtual ObjectResult<proc_Get_WishList_Result> proc_Get_WishList(string useremail)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Get_WishList_Result>("proc_Get_WishList", useremailParameter);
        }
    
        public virtual ObjectResult<proc_GetCart_Result> proc_GetCart(string useremail)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetCart_Result>("proc_GetCart", useremailParameter);
        }
    
        public virtual int proc_Insert_Category(string categoryname, string description)
        {
            var categorynameParameter = categoryname != null ?
                new ObjectParameter("categoryname", categoryname) :
                new ObjectParameter("categoryname", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_Insert_Category", categorynameParameter, descriptionParameter);
        }
    
        public virtual int proc_Insert_Into_Cart(string useremail, Nullable<int> productid, Nullable<int> cartquantity)
        {
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var productidParameter = productid.HasValue ?
                new ObjectParameter("productid", productid) :
                new ObjectParameter("productid", typeof(int));
    
            var cartquantityParameter = cartquantity.HasValue ?
                new ObjectParameter("cartquantity", cartquantity) :
                new ObjectParameter("cartquantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_Insert_Into_Cart", useremailParameter, productidParameter, cartquantityParameter);
        }
    
        public virtual int proc_Insert_Order(string orderdate, string useremail, Nullable<int> productid, Nullable<int> retailerid, Nullable<int> orderquantity, Nullable<double> orderprice)
        {
            var orderdateParameter = orderdate != null ?
                new ObjectParameter("orderdate", orderdate) :
                new ObjectParameter("orderdate", typeof(string));
    
            var useremailParameter = useremail != null ?
                new ObjectParameter("useremail", useremail) :
                new ObjectParameter("useremail", typeof(string));
    
            var productidParameter = productid.HasValue ?
                new ObjectParameter("productid", productid) :
                new ObjectParameter("productid", typeof(int));
    
            var retaileridParameter = retailerid.HasValue ?
                new ObjectParameter("retailerid", retailerid) :
                new ObjectParameter("retailerid", typeof(int));
    
            var orderquantityParameter = orderquantity.HasValue ?
                new ObjectParameter("orderquantity", orderquantity) :
                new ObjectParameter("orderquantity", typeof(int));
    
            var orderpriceParameter = orderprice.HasValue ?
                new ObjectParameter("orderprice", orderprice) :
                new ObjectParameter("orderprice", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_Insert_Order", orderdateParameter, useremailParameter, productidParameter, retaileridParameter, orderquantityParameter, orderpriceParameter);
        }
    
        public virtual ObjectResult<proc_Pending_Products_Result> proc_Pending_Products()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Pending_Products_Result>("proc_Pending_Products");
        }
    
        public virtual int proc_Reject_Product(Nullable<int> productid)
        {
            var productidParameter = productid.HasValue ?
                new ObjectParameter("productid", productid) :
                new ObjectParameter("productid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_Reject_Product", productidParameter);
        }
    
        public virtual int proc_Remove_From_Cart(Nullable<int> cartid, Nullable<int> productid)
        {
            var cartidParameter = cartid.HasValue ?
                new ObjectParameter("cartid", cartid) :
                new ObjectParameter("cartid", typeof(int));
    
            var productidParameter = productid.HasValue ?
                new ObjectParameter("productid", productid) :
                new ObjectParameter("productid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_Remove_From_Cart", cartidParameter, productidParameter);
        }
    
        public virtual int proc_Remove_From_Wishlist(Nullable<int> wishlistid)
        {
            var wishlistidParameter = wishlistid.HasValue ?
                new ObjectParameter("wishlistid", wishlistid) :
                new ObjectParameter("wishlistid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_Remove_From_Wishlist", wishlistidParameter);
        }
    
        public virtual int proc_Remove_Product(Nullable<int> productid)
        {
            var productidParameter = productid.HasValue ?
                new ObjectParameter("productid", productid) :
                new ObjectParameter("productid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_Remove_Product", productidParameter);
        }
    
        public virtual int proc_RemoveProduct(Nullable<int> pid)
        {
            var pidParameter = pid.HasValue ?
                new ObjectParameter("pid", pid) :
                new ObjectParameter("pid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_RemoveProduct", pidParameter);
        }
    
        public virtual ObjectResult<proc_RetailLoginCheck_Result> proc_RetailLoginCheck(string rmail, string pass)
        {
            var rmailParameter = rmail != null ?
                new ObjectParameter("rmail", rmail) :
                new ObjectParameter("rmail", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_RetailLoginCheck_Result>("proc_RetailLoginCheck", rmailParameter, passParameter);
        }
    
        public virtual ObjectResult<proc_Search_Result_Result> proc_Search_Result(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_Search_Result_Result>("proc_Search_Result", searchParameter);
        }
    
        public virtual int proc_Update_Cart(Nullable<int> cartid, Nullable<int> productid, Nullable<int> quantity)
        {
            var cartidParameter = cartid.HasValue ?
                new ObjectParameter("cartid", cartid) :
                new ObjectParameter("cartid", typeof(int));
    
            var productidParameter = productid.HasValue ?
                new ObjectParameter("productid", productid) :
                new ObjectParameter("productid", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_Update_Cart", cartidParameter, productidParameter, quantityParameter);
        }
    
        public virtual int proc_UpdateProduct(string rmail, Nullable<double> pprice, Nullable<int> pquantity, string pdescrip)
        {
            var rmailParameter = rmail != null ?
                new ObjectParameter("rmail", rmail) :
                new ObjectParameter("rmail", typeof(string));
    
            var ppriceParameter = pprice.HasValue ?
                new ObjectParameter("pprice", pprice) :
                new ObjectParameter("pprice", typeof(double));
    
            var pquantityParameter = pquantity.HasValue ?
                new ObjectParameter("pquantity", pquantity) :
                new ObjectParameter("pquantity", typeof(int));
    
            var pdescripParameter = pdescrip != null ?
                new ObjectParameter("pdescrip", pdescrip) :
                new ObjectParameter("pdescrip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_UpdateProduct", rmailParameter, ppriceParameter, pquantityParameter, pdescripParameter);
        }
    
        public virtual ObjectResult<sp_GetAllProduct_Result> sp_GetAllProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllProduct_Result>("sp_GetAllProduct");
        }
    
        public virtual ObjectResult<sp_GetPdtByCategory_Result> sp_GetPdtByCategory(string cname)
        {
            var cnameParameter = cname != null ?
                new ObjectParameter("cname", cname) :
                new ObjectParameter("cname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPdtByCategory_Result>("sp_GetPdtByCategory", cnameParameter);
        }
    
        public virtual ObjectResult<sp_GetPdtByPrice_Result> sp_GetPdtByPrice(Nullable<double> lower, Nullable<double> upper)
        {
            var lowerParameter = lower.HasValue ?
                new ObjectParameter("Lower", lower) :
                new ObjectParameter("Lower", typeof(double));
    
            var upperParameter = upper.HasValue ?
                new ObjectParameter("Upper", upper) :
                new ObjectParameter("Upper", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPdtByPrice_Result>("sp_GetPdtByPrice", lowerParameter, upperParameter);
        }
    
        public virtual ObjectResult<sp_GetPdtByPriceCategory_Result> sp_GetPdtByPriceCategory(Nullable<double> lower, Nullable<double> upper, string cname)
        {
            var lowerParameter = lower.HasValue ?
                new ObjectParameter("Lower", lower) :
                new ObjectParameter("Lower", typeof(double));
    
            var upperParameter = upper.HasValue ?
                new ObjectParameter("Upper", upper) :
                new ObjectParameter("Upper", typeof(double));
    
            var cnameParameter = cname != null ?
                new ObjectParameter("Cname", cname) :
                new ObjectParameter("Cname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPdtByPriceCategory_Result>("sp_GetPdtByPriceCategory", lowerParameter, upperParameter, cnameParameter);
        }
    
        public virtual ObjectResult<sp_SortByPriceAsc_Result> sp_SortByPriceAsc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SortByPriceAsc_Result>("sp_SortByPriceAsc");
        }
    
        public virtual ObjectResult<sp_SortByPriceDesc_Result> sp_SortByPriceDesc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SortByPriceDesc_Result>("sp_SortByPriceDesc");
        }
    }
}
