//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public int orderid { get; set; }
        public string orderdate { get; set; }
        public string useremail { get; set; }
        public int productid { get; set; }
        public Nullable<int> retailerid { get; set; }
        public Nullable<int> orderquantity { get; set; }
        public Nullable<double> orderprice { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblRetailer tblRetailer { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
